### ISSUE TITLE
KeyParseError: Failed to parse (unnamed) as a valid auto format key: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by wootwoot1234** [SmartThingsCommunity/weather-color-light-smartapp-nodejs#16]
I'm getting the following error when adding my app from the MarketPlace and I'm not sure why.  My `smartthings_rsa.pub` has a key that looks like this ({{...}} was put in place of a bunch of random characters):

```
-----BEGIN PUBLIC KEY-----MIIBIjANBg{{...}}bRQIDAQAB-----END PUBLIC KEY-----
```

This is the error I get in the console

```
{ KeyParseError: Failed to parse (unnamed) as a valid auto format key: Cannot read property 'match' of undefined
    at Object.Key.parse [as parseKey] (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/sshpk/lib/key.js:261:10)
    at Object.verifySignature (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/http-signature/lib/verify.js:30:22)
    at signatureIsVerified (/Users/Code/weather-color-light-smartapp-nodejs-master/server.js:64:24)
    at /Users/Code/weather-color-light-smartapp-nodejs-master/server.js:44:52
    at Layer.handle [as handle_request] (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/layer.js:95:5)
    at /Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/index.js:275:10)
    at /Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/raw-body/index.js:224:16)
    at done (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'KeyParseError',
  format: 'auto',
  keyName: '(unnamed)',
  innerErr:
   TypeError: Cannot read property 'match' of undefined
       at Object.read (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/sshpk/lib/formats/pem.js:92:16)
       at Object.read (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/sshpk/lib/formats/auto.js:25:16)
       at Object.Key.parse [as parseKey] (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/sshpk/lib/key.js:252:27)
       at Object.verifySignature (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/http-signature/lib/verify.js:30:22)
       at signatureIsVerified (/Users/Code/weather-color-light-smartapp-nodejs-master/server.js:64:24)
       at /Users/Code/weather-color-light-smartapp-nodejs-master/server.js:44:52
       at Layer.handle [as handle_request] (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/layer.js:95:5)
       at next (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/route.js:137:13)
       at Route.dispatch (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/route.js:112:3)
       at Layer.handle [as handle_request] (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/layer.js:95:5)
       at /Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/index.js:281:22
       at Function.process_params (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/index.js:335:12)
       at next (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/express/lib/router/index.js:275:10)
       at /Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/body-parser/lib/read.js:130:5
       at invokeCallback (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/raw-body/index.js:224:16)
       at done (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/raw-body/index.js:213:7)
       at IncomingMessage.onEnd (/Users/Code/weather-color-light-smartapp-nodejs-master/node_modules/raw-body/index.js:273:7)
       at IncomingMessage.emit (events.js:203:15)
       at endReadableNT (_stream_readable.js:1129:12)
       at process._tickCallback (internal/process/next_tick.js:63:19),
  message:
   'Failed to parse (unnamed) as a valid auto format key: Cannot read property \'match\' of undefined' }
```

On the iOS app, I get the `Something went wrong. Please try to install the SmartApp again.` error.

**Comment by wootwoot1234** [comment]
Never mind.  I found the answer here https://github.com/SmartThingsCommunity/weather-color-light-smartapp-nodejs/issues/6#issuecomment-442081489
