### ISSUE TITLE
Something went wrong. Please try to install the SmartApp again

### ISSUE THREAD

**Issue by fun4stuff** [SmartThingsCommunity/weather-color-light-smartapp-nodejs#19]
I am trying to get this running on my raspberry pi.  Here is what i did:

1. download repository to a dir on my pi
2.put weather map api key in .env file In dir i created above
3. Ran npm install. Installed ngrok. Ran npm start
4. Ran ngrok http 3005 in New terminal
5. Created automation project in Developer Workspace as instructed Using https from Ngrok output
6. Put my key in config/smartthings_rsa.pub
7. Rebooted pi and restarted npm. When I tried to just restart npm i would get an error. Updated automation project with new https from ngrok.
8. When I try and install the smart app in smartthings mobile app i still get "Something went wrong. Please try to install the SmartApp again". Readme says to restart npm as said in step 10. Step 10 does not say this. But.as i said above, i restarted everything. 

The output in the ngrok terminal when i try and install the smart app is "401 unauthorized".

**Comment by fun4stuff** [comment]
Here is the output from weather-color-light-smart app:

`at Authorizer.isAuthorized (/root/weather/weather-color-light-smartapp-nodejs-master/node_modules/@smartthings/smartapp/lib/util/authorizer.js:186:22)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async SmartApp.handleHttpCallback (/root/weather/weather-color-light-smartapp-nodejs-master/node_modules/@smartthings/smartapp/lib/smart-app.js:785:24)
2019-12-21T15:14:30.685Z error: Unauthorized
2019-12-21T15:16:05.240Z error: KeyParseError: Failed to parse (unnamed) as a valid auto format key: Cannot read property 'match' of undefined
at Object.Key.parse [as parseKey] (/root/weather/weather-color-light-smartapp-nodejs-master/node_modules/sshpk/lib/key.js:261:10)
at Object.verifySignature (/root/weather/weather-color-light-smartapp-nodejs-master/node_modules/http-signature/lib/verify.js:30:22)
at Authorizer.isAuthorized (/root/weather/weather-color-light-smartapp-nodejs-master/node_modules/@smartthings/smartapp/lib/util/authorizer.js:186:22)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async SmartApp.handleHttpCallback (/root/weather/weather-color-light-smartapp-nodejs-master/node_modules/@smartthings/smartapp/lib/smart-app.js:785:24)
2019-12-21T15:16:05.241Z error: Unauthorized `

**Comment by fun4stuff** [comment]
I had the smartthings rsa pub file formatted incorrectly. 

Needed spaces after and before the ------
