### ISSUE TITLE
npm install fail , npm start fail about the git source code.

### ISSUE THREAD

**Issue by juhaki** [SmartThingsCommunity/weather-color-light-smartapp-nodejs#3]
The testing environment is the google cloud VM instance - ubuntu 16.04 LTS version.

npm , nodejs , ngrok installed by the apt-get install command.
But.. "npm install" show the warning message. also the "npm start" failed.

 juhaki_park@instance-1:~/src/weather-color-light-smartapp-nodejs$ dpkg -l | grep nodejs
ii  nodejs                           4.2.6~dfsg-1ubuntu4.1                      amd64        evented I/O for V8 javascript
ii  nodejs-dev                       4.2.6~dfsg-1ubuntu4.1                      amd64        evented I/O for V8 javascript (development files)
juhaki_park@instance-1:~/src/weather-color-light-smartapp-nodejs$ dpkg -l | grep npm
ii  node-npmlog                      0.0.4-1                                    all          Logger with custom levels and colored output for Node.js
ii  node-read-package-json           1.2.4-1                                    all          Read package.json for npm module for Node.js
ii  npm                              3.5.2-0ubuntu4                             all          package manager for Node.js
juhaki_park@instance-1:~/src/weather-color-light-smartapp-nodejs$ dpkg -l | grep ngrok
ii  ngrok-client                     1.6+dfsg-1                                 amd64        secure introspectable tunnels to localhost - client part
ii  ngrok-server                     1.6+dfsg-1                                 amd64        secure introspectable tunnels to localhost - server part
juhaki_park@instance-1:~/src/weather-color-light-smartapp-nodejs$

juhaki_park@instance-1:~/src/weather-color-light-smartapp-nodejs$ env | grep WEATHER
WEATHER_API_KEY=7f4673472ca65d667a6f83313d6fdec1
juhaki_park@instance-1:~/src/weather-color-light-smartapp-nodejs$ 

juhaki_park@instance-1:~/src/weather-color-light-smartapp-nodejs$ npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
juhaki_park@instance-1:~/src/weather-color-light-smartapp-nodejs$ npm start

> weather-color-light-SmartApp@1.0.0 start /home/juhaki_park/src/weather-color-light-smartapp-nodejs
> node server.js

sh: 1: node: not found

npm ERR! Linux 4.13.0-1011-gcp
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! weather-color-light-SmartApp@1.0.0 start: `node server.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the weather-color-light-SmartApp@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the weather-color-light-SmartApp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs weather-color-light-SmartApp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls weather-color-light-SmartApp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/juhaki_park/src/weather-color-light-smartapp-nodejs/npm-debug.log
juhaki_park@instance-1:~/src/weather-color-light-smartapp-nodejs$

juhaki_park@instance-1:~/src/weather-color-light-smartapp-nodejs$ cat /home/juhaki_park/src/weather-color-light-smartapp-nodejs/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle weather-color-light-SmartApp@1.0.0~prestart: weather-color-light-SmartApp@1.0.0
6 silly lifecycle weather-color-light-SmartApp@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle weather-color-light-SmartApp@1.0.0~start: weather-color-light-SmartApp@1.0.0
8 verbose lifecycle weather-color-light-SmartApp@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle weather-color-light-SmartApp@1.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/juhaki_park/src/weather-color-light-smartapp-nodejs/node_modules/.bin:/home/juhaki_park/bin:/home/juhaki_park/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle weather-color-light-SmartApp@1.0.0~start: CWD: /home/juhaki_park/src/weather-color-light-smartapp-nodejs
11 silly lifecycle weather-color-light-SmartApp@1.0.0~start: Args: [ '-c', 'node server.js' ]
12 info lifecycle weather-color-light-SmartApp@1.0.0~start: Failed to exec start script
13 verbose stack Error: weather-color-light-SmartApp@1.0.0 start: `node server.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid weather-color-light-SmartApp@1.0.0
15 verbose cwd /home/juhaki_park/src/weather-color-light-smartapp-nodejs
16 error Linux 4.13.0-1011-gcp
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error weather-color-light-SmartApp@1.0.0 start: `node server.js`
24 error spawn ENOENT
25 error Failed at the weather-color-light-SmartApp@1.0.0 start script 'node server.js'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the weather-color-light-SmartApp package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     node server.js
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs weather-color-light-SmartApp
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls weather-color-light-SmartApp
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by juhaki** [comment]
This issue fixed by the below step.

Guide URL : https://nodejs.org/en/download/package-manager/
