### ISSUE TITLE
Key errors, app starts but does not function as intended 

### ISSUE THREAD

**Issue by jallen2281** [SmartThingsCommunity/weather-color-light-smartapp-nodejs#6]
{ KeyParseError: Failed to parse (unnamed) as a valid auto format key: encoding too long
    at Object.Key.parse [as parseKey] (/home/pi/appServer/weatherApp/node_modules/sshpk/lib/key.js:243:10)
    at Object.verifySignature (/home/pi/appServer/weatherApp/node_modules/http-signature/lib/verify.js:30:22)
    at signatureIsVerified (/home/pi/appServer/weatherApp/server.js:62:24)
    at /home/pi/appServer/weatherApp/server.js:43:52
    at Layer.handle [as handle_request] (/home/pi/appServer/weatherApp/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/appServer/weatherApp/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/pi/appServer/weatherApp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pi/appServer/weatherApp/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/appServer/weatherApp/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/pi/appServer/weatherApp/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/appServer/weatherApp/node_modules/express/lib/router/index.js:275:10)
    at /home/pi/appServer/weatherApp/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/pi/appServer/weatherApp/node_modules/raw-body/index.js:224:16)
    at done (/home/pi/appServer/weatherApp/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/pi/appServer/weatherApp/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'KeyParseError',
  format: 'auto',
  keyName: '(unnamed)',
  innerErr:
   { InvalidAsn1Error: encoding too long
       at newInvalidAsn1Error (/home/pi/appServer/weatherApp/node_modules/asn1/lib/ber/errors.js:7:13)
       at Reader.readLength (/home/pi/appServer/weatherApp/node_modules/asn1/lib/ber/reader.js:103:13)
       at Reader.readSequence (/home/pi/appServer/weatherApp/node_modules/asn1/lib/ber/reader.js:136:16)
       at Object.readPkcs8 (/home/pi/appServer/weatherApp/node_modules/sshpk/lib/formats/pkcs8.js:45:6)
       at Object.read (/home/pi/appServer/weatherApp/node_modules/sshpk/lib/formats/pem.js:132:17)
       at Object.read (/home/pi/appServer/weatherApp/node_modules/sshpk/lib/formats/auto.js:24:16)
       at Object.Key.parse [as parseKey] (/home/pi/appServer/weatherApp/node_modules/sshpk/lib/key.js:234:27)
       at Object.verifySignature (/home/pi/appServer/weatherApp/node_modules/http-signature/lib/verify.js:30:22)
       at signatureIsVerified (/home/pi/appServer/weatherApp/server.js:62:24)
       at /home/pi/appServer/weatherApp/server.js:43:52
       at Layer.handle [as handle_request] (/home/pi/appServer/weatherApp/node_modules/express/lib/router/layer.js:95:5)
       at next (/home/pi/appServer/weatherApp/node_modules/express/lib/router/route.js:137:13)
       at Route.dispatch (/home/pi/appServer/weatherApp/node_modules/express/lib/router/route.js:112:3)
       at Layer.handle [as handle_request] (/home/pi/appServer/weatherApp/node_modules/express/lib/router/layer.js:95:5)
       at /home/pi/appServer/weatherApp/node_modules/express/lib/router/index.js:281:22
       at Function.process_params (/home/pi/appServer/weatherApp/node_modules/express/lib/router/index.js:335:12)
       at next (/home/pi/appServer/weatherApp/node_modules/express/lib/router/index.js:275:10)
       at /home/pi/appServer/weatherApp/node_modules/body-parser/lib/read.js:130:5
       at invokeCallback (/home/pi/appServer/weatherApp/node_modules/raw-body/index.js:224:16)
       at done (/home/pi/appServer/weatherApp/node_modules/raw-body/index.js:213:7)
       at IncomingMessage.onEnd (/home/pi/appServer/weatherApp/node_modules/raw-body/index.js:273:7)
       at IncomingMessage.emit (events.js:182:13) name: 'InvalidAsn1Error', message: 'encoding too long' },
  message:
   'Failed to parse (unnamed) as a valid auto format key: encoding too long' }

**Comment by jallen2281** [comment]
An update on this for anyone trying to get it working but having key issues. The correct format is as shown below. Note the newline after "-----BEGIN PUBLIC KEY-----", the newline before "-----END PUBLIC KEY-----",  and the "=" are all required but not output from the smartthings dev workspace. You will also need to remove some spaces.

```
-----BEGIN PUBLIC KEY-----
MIIBBgKBgDI/ranPo8MDfguQfSzqg7mtNlUJLLBK7tlVALyk42agbLTSFcZbs9Yw
t3nSe9yNzZB9ZVrL3O9GXkEb6xvj3dqrog+wWOeFCqNV7BuJNYYC/ef4vlnUFQdw
yswbd7d198qjWBZ7MiZRXxX8qKRln+osTvsDYOMZk93k0cGZgyuJAoGAHkgFohgA
nH93kDPjN4sHaT9WsmZ4ailbMtcnWuLizTRJ2sdGjNrpuwT1R+x1nlYHOeDUSOu6
De0kQJX+HZuQCoha6THsdgcV297krN22FwsDZ1PItXLIr5oC7zcNQaDyAJOIv6BC
ufHQ0IR+L9b9esniMbF8yV0d7EVAaBJiyRk=
-----END PUBLIC KEY-----
```

**Comment by jimmyjames** [comment]
Thanks @jallen2281 for the update. Yes, the HTTP signature parsing is (for good reason) very particular, and even one bad character will cause an error. We've made sure to let the dev workspace team know that the output there can cause problems (would be nice to have a simple copy button or even download the file for you I think!).

We are also considering changing this example app to bypass HTTP verification altogether, since it is just meant as an example and can cause headaches (probably leave code in but commented, because in a real app it is obviously important).

**Comment by jallen2281** [comment]
I think as the examples are meant for learning, they should definitely
include the verification. The copy button or a code box with proper
formatting would be a great feature.
